export const CUSTOM_FONT_FILES = [
  { file: "New Fonts/AbrilFatface-Regular.ttf", name: "Abril Fatface" },
  { file: "New Fonts/AlfaSlabOne-Regular.ttf", name: "Alfa Slab One" },
  {
    file: "New Fonts/alte-din-1451-mittelschrift.regular.ttf",
    name: "Alte DIN 1451 Mittelschrift",
  },
  { file: "New Fonts/Anton-Regular.ttf", name: "Anton" },
  { file: "New Fonts/Arimo-Bold.ttf", name: "Arimo Bold" },
  { file: "New Fonts/Arimo-Italic.ttf", name: "Arimo Italic" },
  { file: "New Fonts/Arimo-Medium.ttf", name: "Arimo Medium" },
  {
    file: "New Fonts/Arimo-MediumItalic.ttf",
    name: "Arimo Medium Italic",
  },
  { file: "New Fonts/Arimo-Regular.ttf", name: "Arimo" },
  { file: "New Fonts/Audiowide-Regular.ttf", name: "Audiowide" },
  { file: "New Fonts/Baloo2-Bold.ttf", name: "Baloo 2 Bold" },
  { file: "New Fonts/Baloo2-Medium.ttf", name: "Baloo 2 Medium" },
  { file: "New Fonts/Baloo2-Regular.ttf", name: "Baloo 2" },
  { file: "New Fonts/BreeSerif-Regular.ttf", name: "Bree Serif" },
  { file: "New Fonts/Caveat-Bold.ttf", name: "Caveat Bold" },
  { file: "New Fonts/Caveat-Medium.ttf", name: "Caveat Medium" },
  { file: "New Fonts/Caveat-Regular.ttf", name: "Caveat" },
  {
    file: "New Fonts/Caveat-VariableFont_wght.ttf",
    name: "Caveat Variable",
  },
  { file: "New Fonts/ComicNeue-Bold.ttf", name: "Comic Neue Bold" },
  {
    file: "New Fonts/ComicNeue-BoldItalic.ttf",
    name: "Comic Neue Bold Italic",
  },
  { file: "New Fonts/ComicNeue-Italic.ttf", name: "Comic Neue Italic" },
  { file: "New Fonts/ComicNeue-Regular.ttf", name: "Comic Neue" },
  { file: "New Fonts/ComicRelief-Bold.ttf", name: "Comic Relief Bold" },
  { file: "New Fonts/ComicRelief-Regular.ttf", name: "Comic Relief" },
  { file: "New Fonts/Courgette-Regular.ttf", name: "Courgette" },
  { file: "New Fonts/D-DIN.otf", name: "D-DIN" },
  { file: "New Fonts/D-DIN-Bold.otf", name: "D-DIN Bold" },
  { file: "New Fonts/D-DINCondensed.otf", name: "D-DIN Condensed" },
  {
    file: "New Fonts/D-DINCondensed-Bold.otf",
    name: "D-DIN Condensed Bold",
  },
  { file: "New Fonts/D-DIN-Italic.otf", name: "D-DIN Italic" },
  { file: "New Fonts/DancingScript-Bold.ttf", name: "Dancing Script Bold" },
  {
    file: "New Fonts/DancingScript-Medium.ttf",
    name: "Dancing Script Medium",
  },
  { file: "New Fonts/DancingScript-Regular.ttf", name: "Dancing Script" },
  {
    file: "New Fonts/DancingScript-VariableFont_wght.ttf",
    name: "Dancing Script Variable",
  },
  { file: "New Fonts/GoogleSans-Bold.ttf", name: "Google Sans Bold" },
  {
    file: "New Fonts/GoogleSans-BoldItalic.ttf",
    name: "Google Sans Bold Italic",
  },
  { file: "New Fonts/GoogleSans-Italic.ttf", name: "Google Sans Italic" },
  { file: "New Fonts/GoogleSans-Medium.ttf", name: "Google Sans Medium" },
  {
    file: "New Fonts/GoogleSans-MediumItalic.ttf",
    name: "Google Sans Medium Italic",
  },
  { file: "New Fonts/GoogleSans-Regular.ttf", name: "Google Sans" },
  { file: "New Fonts/GreatVibes-Regular.ttf", name: "Great Vibes" },
  { file: "New Fonts/Handlee-Regular.ttf", name: "Handlee" },
  { file: "New Fonts/Inter-Bold.ttf", name: "Inter Bold" },
  { file: "New Fonts/Inter-BoldItalic.ttf", name: "Inter Bold Italic" },
  { file: "New Fonts/Inter-Italic.ttf", name: "Inter Italic" },
  { file: "New Fonts/Inter-Medium.ttf", name: "Inter Medium" },
  { file: "New Fonts/Inter-MediumItalic.ttf", name: "Inter Medium Italic" },
  { file: "New Fonts/Inter-Regular.ttf", name: "Inter" },
  { file: "New Fonts/Kalam-Bold.ttf", name: "Kalam Bold" },
  { file: "New Fonts/Kalam-Regular.ttf", name: "Kalam" },
  { file: "New Fonts/KeaniaOne-Regular.ttf", name: "Keania One" },
  { file: "New Fonts/Lobster-Regular.ttf", name: "Lobster" },
  { file: "New Fonts/Montserrat-Bold.ttf", name: "Montserrat Bold" },
  { file: "New Fonts/Montserrat-Italic.ttf", name: "Montserrat Italic" },
  { file: "New Fonts/Montserrat-Medium.ttf", name: "Montserrat Medium" },
  { file: "New Fonts/Montserrat-Regular.ttf", name: "Montserrat" },
  { file: "New Fonts/Oswald-Bold.ttf", name: "Oswald Bold" },
  { file: "New Fonts/Oswald-Medium.ttf", name: "Oswald Medium" },
  { file: "New Fonts/Oswald-Regular.ttf", name: "Oswald" },
  { file: "New Fonts/PirataOne-Regular.ttf", name: "Pirata One" },
  { file: "New Fonts/Roboto-Bold.ttf", name: "Roboto Bold" },
  {
    file: "New Fonts/Roboto-BoldItalic.ttf",
    name: "Roboto Bold Italic",
  },
  { file: "New Fonts/Roboto-Italic.ttf", name: "Roboto Italic" },
  { file: "New Fonts/Roboto-Medium.ttf", name: "Roboto Medium" },
  {
    file: "New Fonts/Roboto-MediumItalic.ttf",
    name: "Roboto Medium Italic",
  },
  { file: "New Fonts/Roboto-Regular.ttf", name: "Roboto" },
  { file: "New Fonts/Satisfy-Regular.ttf", name: "Satisfy" },
  { file: "New Fonts/Teko-Bold.ttf", name: "Teko Bold" },
  { file: "New Fonts/Teko-Medium.ttf", name: "Teko Medium" },
  { file: "New Fonts/Teko-Regular.ttf", name: "Teko" },
  {
    file: "New Fonts/Teko-VariableFont_wght.ttf",
    name: "Teko Variable",
  },
  { file: "New Fonts/Tinos-Bold.ttf", name: "Tinos Bold" },
  { file: "New Fonts/Tinos-BoldItalic.ttf", name: "Tinos Bold Italic" },
  { file: "New Fonts/Tinos-Italic.ttf", name: "Tinos Italic" },
  { file: "New Fonts/Tinos-Regular.ttf", name: "Tinos" },
];

/*
export const CUSTOM_FONT_FILES = [
  { file: "AbrilFatface-Regular.ttf", name: "Abril Fatface" },
  { file: "AlfaSlabOne-Regular.ttf", name: "Alfa Slab One" },
  { file: "ArialMT.ttf", name: "Arial" },
  { file: "Arial-BoldMT.ttf", name: "Arial Bold" },
  { file: "Arial-ItalicMT.ttf", name: "Arial Italic" },
  { file: "Arial-BoldItalicMT.ttf", name: "Arial Bold Italic" },
  { file: "ArialNarrow.ttf", name: "Arial Narrow" },
  { file: "ArialNarrow-Bold.ttf", name: "Arial Narrow Bold" },
  { file: "Audiowide-Regular.ttf", name: "Audiowide" },
  { file: "Baloo-Regular.ttf", name: "Baloo" },
  { file: "Baloo2-Regular.ttf", name: "Baloo 2" },
  { file: "Baloo2-Bold.ttf", name: "Baloo 2 Bold" },
  { file: "Baloo2-Medium.ttf", name: "Baloo 2 Medium" },
  { file: "BreeSerif-Regular.ttf", name: "Bree Serif" },
  { file: "ComicSansMS.ttf", name: "Comic Sans MS" },
  { file: "ComicSansMS-Bold.ttf", name: "Comic Sans MS Bold" },
  { file: "ComicSansMS-BoldItalic.ttf", name: "Comic Sans MS Bold Italic" },
  { file: "Courgette-Regular.ttf", name: "Courgette" },
  { file: "DancingScript-Bold.ttf", name: "Dancing Script Bold" },
  { file: "Daniel-Bold.ttf", name: "Daniel Bold" },
  { file: "DIN1451Engschrift.ttf", name: "DIN 1451 Engschrift" },
  { file: "DIN1451Mittelschrift.ttf", name: "DIN 1451 Mittelschrift" },
  { file: "exmouth_.ttf", name: "Exmouth" },
  { file: "Exo2-Regular.ttf", name: "Exo 2" },
  { file: "Exo2-Bold.ttf", name: "Exo 2 Bold" },
  { file: "Exo2-Medium.ttf", name: "Exo 2 Medium" },
  { file: "Exo2-BoldItalic.ttf", name: "Exo 2 Bold Italic" },
  { file: "Exo2-MediumItalic.ttf", name: "Exo 2 Medium Italic" },
  { file: "Gotham-Medium.ttf", name: "Gotham Medium" },
  { file: "Gotham-Bold.ttf", name: "Gotham Bold" },
  { file: "Gotham-MediumItalic.ttf", name: "Gotham Medium Italic" },
  { file: "Gotham-BoldItalic.ttf", name: "Gotham Bold Italic" },
  { file: "GreatVibes-Regular.ttf", name: "Great Vibes" },
  { file: "Handlee-Regular.ttf", name: "Handlee" },
  { file: "ImpactLTStd.ttf", name: "Impact" },
  { file: "Inter-Regular.ttf", name: "Inter" },
  { file: "Inter-Bold.ttf", name: "Inter Bold" },
  { file: "Inter-Italic.ttf", name: "Inter Italic" },
  { file: "Inter-ExtraBoldItalic.ttf", name: "Inter Extra Bold Italic" },
  { file: "Kalam-Regular.ttf", name: "Kalam" },
  { file: "Kalam-Bold.ttf", name: "Kalam Bold" },
  { file: "KeaniaOne-Regular.ttf", name: "Keania One" },
  { file: "Lobster-Regular.ttf", name: "Lobster" },
  { file: "Merriweather-Regular.ttf", name: "Merriweather" },
  { file: "Merriweather-BoldItalic.ttf", name: "Merriweather Bold Italic" },
  { file: "Merriweather-BlackItalic.ttf", name: "Merriweather Black Italic" },
  { file: "Oswald-Regular.ttf", name: "Oswald" },
  { file: "Oswald-Bold.ttf", name: "Oswald Bold" },
  { file: "Pacifico-Regular.ttf", name: "Pacifico" },
  { file: "PatuaOne-Regular.ttf", name: "Patua One" },
  { file: "Roboto-Regular.ttf", name: "Roboto" },
  { file: "Roboto-Bold.ttf", name: "Roboto Bold" },
  { file: "Roboto-Italic.ttf", name: "Roboto Italic" },
  { file: "Roboto-BoldItalic.ttf", name: "Roboto Bold Italic" },
  { file: "Rubik-Regular.ttf", name: "Rubik" },
  { file: "Rubik-Bold.ttf", name: "Rubik Bold" },
  { file: "Rubik-BoldItalic.ttf", name: "Rubik Bold Italic" },
  { file: "Sacramento-Regular.ttf", name: "Sacramento" },
  { file: "Satisfy-Regular.ttf", name: "Satisfy" },
  { file: "StardosStencil-Regular.ttf", name: "Stardos Stencil" },
  { file: "StardosStencil-Bold.ttf", name: "Stardos Stencil Bold" },
  { file: "Teko-Regular.ttf", name: "Teko" },
  { file: "Teko-SemiBold.ttf", name: "Teko SemiBold" },
  { file: "Teko-Bold.ttf", name: "Teko Bold" },
  { file: "TimesNewRomanMTStd.ttf", name: "Times New Roman" },
  { file: "TimesNewRomanMTStd-Bold.ttf", name: "Times New Roman Bold" },
  { file: "TimesNewRomanMTStd-Italic.ttf", name: "Times New Roman Italic" },
  {
    file: "TimesNewRomanMTStd-BoldIt.ttf",
    name: "Times New Roman Bold Italic",
  },
  { file: "VT323-Regular.ttf", name: "VT323" },
];
*/
