export const CUSTOM_FONT_FILES = [
  { file: "AbrilFatface-Regular.ttf", name: "Abril Fatface" },
  { file: "AlfaSlabOne-Regular.ttf", name: "Alfa Slab One" },
  { file: "ArialMT.ttf", name: "Arial" },
  { file: "Arial-BoldMT.ttf", name: "Arial Bold" },
  { file: "Arial-ItalicMT.ttf", name: "Arial Italic" },
  { file: "Arial-BoldItalicMT.ttf", name: "Arial Bold Italic" },
  { file: "ArialNarrow.ttf", name: "Arial Narrow" },
  { file: "ArialNarrow-Bold.ttf", name: "Arial Narrow Bold" },
  { file: "Audiowide-Regular.ttf", name: "Audiowide" },
  { file: "Baloo-Regular.ttf", name: "Baloo" },
  { file: "Baloo2-Regular.ttf", name: "Baloo 2" },
  { file: "Baloo2-Bold.ttf", name: "Baloo 2 Bold" },
  { file: "Baloo2-Medium.ttf", name: "Baloo 2 Medium" },
  { file: "BreeSerif-Regular.ttf", name: "Bree Serif" },
  { file: "ComicSansMS.ttf", name: "Comic Sans MS" },
  { file: "ComicSansMS-Bold.ttf", name: "Comic Sans MS Bold" },
  { file: "ComicSansMS-BoldItalic.ttf", name: "Comic Sans MS Bold Italic" },
  { file: "Courgette-Regular.ttf", name: "Courgette" },
  { file: "DancingScript-Bold.ttf", name: "Dancing Script Bold" },
  { file: "Daniel-Bold.ttf", name: "Daniel Bold" },
  { file: "DIN1451Engschrift.ttf", name: "DIN 1451 Engschrift" },
  { file: "DIN1451Mittelschrift.ttf", name: "DIN 1451 Mittelschrift" },
  { file: "exmouth_.ttf", name: "Exmouth" },
  { file: "Exo2-Regular.ttf", name: "Exo 2" },
  { file: "Exo2-Bold.ttf", name: "Exo 2 Bold" },
  { file: "Exo2-Medium.ttf", name: "Exo 2 Medium" },
  { file: "Exo2-BoldItalic.ttf", name: "Exo 2 Bold Italic" },
  { file: "Exo2-MediumItalic.ttf", name: "Exo 2 Medium Italic" },
  { file: "Gotham-Medium.ttf", name: "Gotham Medium" },
  { file: "Gotham-Bold.ttf", name: "Gotham Bold" },
  { file: "Gotham-MediumItalic.ttf", name: "Gotham Medium Italic" },
  { file: "Gotham-BoldItalic.ttf", name: "Gotham Bold Italic" },
  { file: "GreatVibes-Regular.ttf", name: "Great Vibes" },
  { file: "Handlee-Regular.ttf", name: "Handlee" },
  { file: "ImpactLTStd.ttf", name: "Impact" },
  { file: "Inter-Regular.ttf", name: "Inter" },
  { file: "Inter-Bold.ttf", name: "Inter Bold" },
  { file: "Inter-Italic.ttf", name: "Inter Italic" },
  { file: "Inter-ExtraBoldItalic.ttf", name: "Inter Extra Bold Italic" },
  { file: "Kalam-Regular.ttf", name: "Kalam" },
  { file: "Kalam-Bold.ttf", name: "Kalam Bold" },
  { file: "KeaniaOne-Regular.ttf", name: "Keania One" },
  { file: "Lobster-Regular.ttf", name: "Lobster" },
  { file: "Merriweather-Regular.ttf", name: "Merriweather" },
  { file: "Merriweather-BoldItalic.ttf", name: "Merriweather Bold Italic" },
  { file: "Merriweather-BlackItalic.ttf", name: "Merriweather Black Italic" },
  { file: "Oswald-Regular.ttf", name: "Oswald" },
  { file: "Oswald-Bold.ttf", name: "Oswald Bold" },
  { file: "Pacifico-Regular.ttf", name: "Pacifico" },
  { file: "PatuaOne-Regular.ttf", name: "Patua One" },
  { file: "Roboto-Regular.ttf", name: "Roboto" },
  { file: "Roboto-Bold.ttf", name: "Roboto Bold" },
  { file: "Roboto-Italic.ttf", name: "Roboto Italic" },
  { file: "Roboto-BoldItalic.ttf", name: "Roboto Bold Italic" },
  { file: "Rubik-Regular.ttf", name: "Rubik" },
  { file: "Rubik-Bold.ttf", name: "Rubik Bold" },
  { file: "Rubik-BoldItalic.ttf", name: "Rubik Bold Italic" },
  { file: "Sacramento-Regular.ttf", name: "Sacramento" },
  { file: "Satisfy-Regular.ttf", name: "Satisfy" },
  { file: "StardosStencil-Regular.ttf", name: "Stardos Stencil" },
  { file: "StardosStencil-Bold.ttf", name: "Stardos Stencil Bold" },
  { file: "Teko-Regular.ttf", name: "Teko" },
  { file: "Teko-SemiBold.ttf", name: "Teko SemiBold" },
  { file: "Teko-Bold.ttf", name: "Teko Bold" },
  { file: "TimesNewRomanMTStd.ttf", name: "Times New Roman" },
  { file: "TimesNewRomanMTStd-Bold.ttf", name: "Times New Roman Bold" },
  { file: "TimesNewRomanMTStd-Italic.ttf", name: "Times New Roman Italic" },
  {
    file: "TimesNewRomanMTStd-BoldIt.ttf",
    name: "Times New Roman Bold Italic",
  },
  { file: "VT323-Regular.ttf", name: "VT323" },
];
